[workspace]
members = [
    "day1-0",
    "day1-5",
    "day2-0",
    "day2-5",
    "day3-0",
    "day3-5", 
    "day4-0",
    "day4-5",
    "day5-0", 
    "day5-5", 
    "day6-0",
    "day6-5",
    "day7-0",
]

resolver = "3"
